# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ceba22641008f51e220daab908d6ffdc9953bb5758d9c05db54aa8dffac920767c0e10d2732ae66b221612a844bed2099cffc8b24187a18dc2e205a93bd53a39

test:
  secret_key_base: b6581439a46dba158aa1b60b60512281c1adafbeba3599f0d1f7873c9f3f4c23da095d689d6ba8d40bc889d1ada96dec6c7f3d7e67173a6d9f84bc75a3a2a98f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
